"""Product catalog reference for Dukaan Saathi.

Static per-SKU reference data: name, brand, category, unit, MRP, purchase price,
shelf life (days), reorder level, HSN. Consumed at runtime by ``shelf_life`` and
``resolve``. This is the shop's product master, not generated data.
"""
from __future__ import annotations

CATALOG: list[dict] = [{'name': 'Aashirvaad Atta 5kg',
  'category': 'Staples',
  'brand': 'Aashirvaad',
  'unit': '5kg pack',
  'mrp': 330.0,
  'purchase_price': 310.2,
  'shelf_life_days': 180,
  'reorder_level': 8,
  'hsn': '1101',
  'supplier': 'Sharma Distributors',
  'qty': 22},
 {'name': 'Fortune Chakki Fresh Atta 5kg',
  'category': 'Staples',
  'brand': 'Fortune',
  'unit': '5kg pack',
  'mrp': 295.0,
  'purchase_price': 277.3,
  'shelf_life_days': 180,
  'reorder_level': 5,
  'hsn': '1101',
  'supplier': 'Patel Wholesale Mandi',
  'qty': 12},
 {'name': 'Loose Chakki Atta',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 42.0,
  'purchase_price': 37.8,
  'shelf_life_days': 150,
  'reorder_level': 20,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 35},
 {'name': 'India Gate Basmati Classic 1kg',
  'category': 'Staples',
  'brand': 'India Gate',
  'unit': '1kg pack',
  'mrp': 198.0,
  'purchase_price': 184.14,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '1006',
  'supplier': 'Patel Wholesale Mandi',
  'qty': 14},
 {'name': 'Sona Masoori Rice',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 62.0,
  'purchase_price': 57.04,
  'shelf_life_days': 365,
  'reorder_level': 25,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 48},
 {'name': 'Tata Sampann Toor Dal 1kg',
  'category': 'Staples',
  'brand': 'Tata Sampann',
  'unit': '1kg pack',
  'mrp': 244.0,
  'purchase_price': 224.48,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0713',
  'supplier': 'Ganesh Provision Stores',
  'qty': 13},
 {'name': 'Loose Toor Dal',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 148.0,
  'purchase_price': 134.68,
  'shelf_life_days': 300,
  'reorder_level': 15,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 26},
 {'name': 'Tata Sampann Moong Dal 500g',
  'category': 'Staples',
  'brand': 'Tata Sampann',
  'unit': '500g pack',
  'mrp': 107.0,
  'purchase_price': 97.37,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0713',
  'supplier': 'Ganesh Provision Stores',
  'qty': 12},
 {'name': 'Loose Masoor Dal',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 105.0,
  'purchase_price': 95.55,
  'shelf_life_days': 300,
  'reorder_level': 12,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 9},
 {'name': 'Rajma Chitra',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 160.0,
  'purchase_price': 144.0,
  'shelf_life_days': 300,
  'reorder_level': 8,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 14},
 {'name': 'Madhur Sugar 1kg',
  'category': 'Staples',
  'brand': 'Madhur',
  'unit': '1kg pack',
  'mrp': 65.0,
  'purchase_price': 60.45,
  'shelf_life_days': None,
  'reorder_level': 12,
  'hsn': '1701',
  'supplier': 'Patel Wholesale Mandi',
  'qty': 30},
 {'name': 'Loose Sugar',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 46.0,
  'purchase_price': 42.32,
  'shelf_life_days': None,
  'reorder_level': 30,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 55},
 {'name': 'Tata Salt 1kg',
  'category': 'Staples',
  'brand': 'Tata',
  'unit': '1kg pack',
  'mrp': 30.0,
  'purchase_price': 27.0,
  'shelf_life_days': None,
  'reorder_level': 15,
  'hsn': '2501',
  'supplier': 'Ganesh Provision Stores',
  'qty': 40},
 {'name': 'Loose Poha (Flattened Rice)',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 70.0,
  'purchase_price': 63.0,
  'shelf_life_days': 240,
  'reorder_level': 8,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 15},
 {'name': 'Loose Besan (Gram Flour)',
  'category': 'Staples',
  'brand': 'Local',
  'unit': '1kg loose',
  'mrp': 90.0,
  'purchase_price': 81.0,
  'shelf_life_days': 180,
  'reorder_level': 8,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 13},
 {'name': 'Fortune Sunlite Sunflower Oil 1L',
  'category': 'Edible Oil',
  'brand': 'Fortune',
  'unit': '1L pouch',
  'mrp': 165.0,
  'purchase_price': 156.75,
  'shelf_life_days': 270,
  'reorder_level': 10,
  'hsn': '1512',
  'supplier': 'Marico D2R',
  'qty': 24},
 {'name': 'Saffola Gold Oil 1L',
  'category': 'Edible Oil',
  'brand': 'Saffola',
  'unit': '1L pouch',
  'mrp': 208.0,
  'purchase_price': 197.6,
  'shelf_life_days': 270,
  'reorder_level': 8,
  'hsn': '1512',
  'supplier': 'Marico D2R',
  'qty': 18},
 {'name': 'Saffola Gold Oil 5L',
  'category': 'Edible Oil',
  'brand': 'Saffola',
  'unit': '5L jar',
  'mrp': 1279.0,
  'purchase_price': 1227.84,
  'shelf_life_days': 270,
  'reorder_level': 3,
  'hsn': '1512',
  'supplier': 'Marico D2R',
  'qty': 6},
 {'name': 'Fortune Mustard Oil 1L',
  'category': 'Edible Oil',
  'brand': 'Fortune',
  'unit': '1L pouch',
  'mrp': 175.0,
  'purchase_price': 166.25,
  'shelf_life_days': 270,
  'reorder_level': 8,
  'hsn': '1514',
  'supplier': 'Marico D2R',
  'qty': 20},
 {'name': 'Fortune Mustard Oil 5L',
  'category': 'Edible Oil',
  'brand': 'Fortune',
  'unit': '5L jar',
  'mrp': 919.0,
  'purchase_price': 882.24,
  'shelf_life_days': 270,
  'reorder_level': 3,
  'hsn': '1514',
  'supplier': 'Marico D2R',
  'qty': 5},
 {'name': 'Fortune Refined Soyabean Oil 1L',
  'category': 'Edible Oil',
  'brand': 'Fortune',
  'unit': '1L pouch',
  'mrp': 150.0,
  'purchase_price': 142.5,
  'shelf_life_days': 270,
  'reorder_level': 6,
  'hsn': '1507',
  'supplier': 'Marico D2R',
  'qty': 13},
 {'name': 'Amul Pure Ghee 1L',
  'category': 'Edible Oil',
  'brand': 'Amul',
  'unit': '1L tin',
  'mrp': 610.0,
  'purchase_price': 573.4,
  'shelf_life_days': 240,
  'reorder_level': 5,
  'hsn': '0405',
  'supplier': 'Amul Parlour Depot',
  'qty': 11},
 {'name': 'Amul Pure Ghee 500ml',
  'category': 'Edible Oil',
  'brand': 'Amul',
  'unit': '500ml tin',
  'mrp': 315.0,
  'purchase_price': 296.1,
  'shelf_life_days': 240,
  'reorder_level': 6,
  'hsn': '0405',
  'supplier': 'Amul Parlour Depot',
  'qty': 14},
 {'name': 'Patanjali Cow Ghee 1L',
  'category': 'Edible Oil',
  'brand': 'Patanjali',
  'unit': '1L jar',
  'mrp': 650.0,
  'purchase_price': 604.5,
  'shelf_life_days': 240,
  'reorder_level': 3,
  'hsn': '0405',
  'supplier': 'Ganesh Provision Stores',
  'qty': 6},
 {'name': 'Amul Gold Milk 500ml',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '500ml pouch',
  'mrp': 34.0,
  'purchase_price': 31.62,
  'shelf_life_days': 3,
  'reorder_level': 30,
  'hsn': '0401',
  'supplier': 'Amul Parlour Depot',
  'qty': 40},
 {'name': 'Amul Taaza Milk 500ml',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '500ml pouch',
  'mrp': 28.0,
  'purchase_price': 26.04,
  'shelf_life_days': 3,
  'reorder_level': 30,
  'hsn': '0401',
  'supplier': 'Amul Parlour Depot',
  'qty': 36},
 {'name': 'Amul Gold Milk 1L',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '1L pouch',
  'mrp': 67.0,
  'purchase_price': 62.31,
  'shelf_life_days': 3,
  'reorder_level': 20,
  'hsn': '0401',
  'supplier': 'Amul Parlour Depot',
  'qty': 22},
 {'name': 'Mother Dairy Full Cream Milk 500ml',
  'category': 'Dairy',
  'brand': 'Mother Dairy',
  'unit': '500ml pouch',
  'mrp': 34.0,
  'purchase_price': 31.62,
  'shelf_life_days': 3,
  'reorder_level': 25,
  'hsn': '0401',
  'supplier': 'Mother Dairy Booth',
  'qty': 28},
 {'name': 'Mother Dairy Token Milk 1L',
  'category': 'Dairy',
  'brand': 'Mother Dairy',
  'unit': '1L pouch',
  'mrp': 60.0,
  'purchase_price': 56.4,
  'shelf_life_days': 2,
  'reorder_level': 20,
  'hsn': '0401',
  'supplier': 'Mother Dairy Booth',
  'qty': 7},
 {'name': 'Amul Taaza UHT Milk 1L (Tetra)',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '1L tetra',
  'mrp': 79.0,
  'purchase_price': 72.68,
  'shelf_life_days': 150,
  'reorder_level': 8,
  'hsn': '0401',
  'supplier': 'Amul Parlour Depot',
  'qty': 16},
 {'name': 'Amul Butter 100g',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '100g pack',
  'mrp': 58.0,
  'purchase_price': 53.36,
  'shelf_life_days': 180,
  'reorder_level': 12,
  'hsn': '0405',
  'supplier': 'Amul Parlour Depot',
  'qty': 26},
 {'name': 'Amul Fresh Paneer 200g',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '200g pack',
  'mrp': 99.0,
  'purchase_price': 91.08,
  'shelf_life_days': 6,
  'reorder_level': 8,
  'hsn': '0406',
  'supplier': 'Amul Parlour Depot',
  'qty': 10},
 {'name': 'Mother Dairy Dahi 400g',
  'category': 'Dairy',
  'brand': 'Mother Dairy',
  'unit': '400g cup',
  'mrp': 45.0,
  'purchase_price': 40.95,
  'shelf_life_days': 14,
  'reorder_level': 12,
  'hsn': '0403',
  'supplier': 'Mother Dairy Booth',
  'qty': 18},
 {'name': 'Amul Masti Dahi 200g',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '200g cup',
  'mrp': 25.0,
  'purchase_price': 22.75,
  'shelf_life_days': 14,
  'reorder_level': 12,
  'hsn': '0403',
  'supplier': 'Amul Parlour Depot',
  'qty': 20},
 {'name': 'Amul Cheese Slices 100g',
  'category': 'Dairy',
  'brand': 'Amul',
  'unit': '100g pack',
  'mrp': 85.0,
  'purchase_price': 74.8,
  'shelf_life_days': 180,
  'reorder_level': 5,
  'hsn': '0406',
  'supplier': 'Amul Parlour Depot',
  'qty': 11},
 {'name': 'Nestle Everyday Dairy Whitener 400g',
  'category': 'Dairy',
  'brand': 'Nestle',
  'unit': '400g pack',
  'mrp': 245.0,
  'purchase_price': 225.4,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '0402',
  'supplier': 'Verma Agencies',
  'qty': 8},
 {'name': 'MDH Garam Masala 100g',
  'category': 'Spices',
  'brand': 'MDH',
  'unit': '100g box',
  'mrp': 108.0,
  'purchase_price': 95.04,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0910',
  'supplier': 'Ganesh Provision Stores',
  'qty': 14},
 {'name': 'Everest Garam Masala 100g',
  'category': 'Spices',
  'brand': 'Everest',
  'unit': '100g box',
  'mrp': 106.0,
  'purchase_price': 93.28,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0910',
  'supplier': 'Ganesh Provision Stores',
  'qty': 13},
 {'name': 'Everest Turmeric (Haldi) Powder 200g',
  'category': 'Spices',
  'brand': 'Everest',
  'unit': '200g pack',
  'mrp': 80.0,
  'purchase_price': 69.6,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '0910',
  'supplier': 'Ganesh Provision Stores',
  'qty': 16},
 {'name': 'Catch Red Chilli Powder 100g',
  'category': 'Spices',
  'brand': 'Catch',
  'unit': '100g pack',
  'mrp': 60.0,
  'purchase_price': 52.2,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0904',
  'supplier': 'Ganesh Provision Stores',
  'qty': 12},
 {'name': 'Everest Coriander (Dhania) Powder 100g',
  'category': 'Spices',
  'brand': 'Everest',
  'unit': '100g pack',
  'mrp': 45.0,
  'purchase_price': 39.15,
  'shelf_life_days': 365,
  'reorder_level': 6,
  'hsn': '0909',
  'supplier': 'Ganesh Provision Stores',
  'qty': 13},
 {'name': 'Everest Chhole Masala 100g',
  'category': 'Spices',
  'brand': 'Everest',
  'unit': '100g box',
  'mrp': 78.0,
  'purchase_price': 67.86,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '0910',
  'supplier': 'Ganesh Provision Stores',
  'qty': 8},
 {'name': 'Tata Sampann Cumin (Jeera) Whole 100g',
  'category': 'Spices',
  'brand': 'Tata Sampann',
  'unit': '100g pack',
  'mrp': 90.0,
  'purchase_price': 79.2,
  'shelf_life_days': 730,
  'reorder_level': 5,
  'hsn': '0909',
  'supplier': 'Ganesh Provision Stores',
  'qty': 11},
 {'name': 'Loose Mustard Seeds (Rai)',
  'category': 'Spices',
  'brand': 'Local',
  'unit': '100g loose',
  'mrp': 25.0,
  'purchase_price': 21.25,
  'shelf_life_days': 730,
  'reorder_level': 6,
  'hsn': None,
  'supplier': 'Patel Wholesale Mandi',
  'qty': 14},
 {'name': 'Catch Hing (Asafoetida) 25g',
  'category': 'Spices',
  'brand': 'Catch',
  'unit': '25g box',
  'mrp': 70.0,
  'purchase_price': 60.9,
  'shelf_life_days': 540,
  'reorder_level': 3,
  'hsn': '1301',
  'supplier': 'Ganesh Provision Stores',
  'qty': 7},
 {'name': 'Sendha Namak (Rock Salt)',
  'category': 'Spices',
  'brand': 'Local',
  'unit': '200g pack',
  'mrp': 40.0,
  'purchase_price': 34.0,
  'shelf_life_days': None,
  'reorder_level': 5,
  'hsn': '2501',
  'supplier': 'Ganesh Provision Stores',
  'qty': 12},
 {'name': 'Parle-G Biscuit Rs5',
  'category': 'Biscuits',
  'brand': 'Parle',
  'unit': '55g pack',
  'mrp': 5.0,
  'purchase_price': 4.45,
  'shelf_life_days': 240,
  'reorder_level': 60,
  'hsn': '1905',
  'supplier': 'Patel Wholesale Mandi',
  'qty': 130},
 {'name': 'Parle-G Biscuit Rs10',
  'category': 'Biscuits',
  'brand': 'Parle',
  'unit': '140g pack',
  'mrp': 10.0,
  'purchase_price': 8.9,
  'shelf_life_days': 240,
  'reorder_level': 40,
  'hsn': '1905',
  'supplier': 'Patel Wholesale Mandi',
  'qty': 96},
 {'name': 'Parle-G Gold 1kg',
  'category': 'Biscuits',
  'brand': 'Parle',
  'unit': '1kg pack',
  'mrp': 160.0,
  'purchase_price': 142.4,
  'shelf_life_days': 240,
  'reorder_level': 6,
  'hsn': '1905',
  'supplier': 'Sharma Distributors',
  'qty': 14},
 {'name': 'Britannia Good Day Cashew 100g',
  'category': 'Biscuits',
  'brand': 'Britannia',
  'unit': '100g pack',
  'mrp': 35.0,
  'purchase_price': 30.8,
  'shelf_life_days': 270,
  'reorder_level': 12,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 28},
 {'name': 'Britannia Marie Gold 250g',
  'category': 'Biscuits',
  'brand': 'Britannia',
  'unit': '250g pack',
  'mrp': 40.0,
  'purchase_price': 35.2,
  'shelf_life_days': 270,
  'reorder_level': 10,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 22},
 {'name': 'Britannia Bourbon 150g',
  'category': 'Biscuits',
  'brand': 'Britannia',
  'unit': '150g pack',
  'mrp': 35.0,
  'purchase_price': 30.45,
  'shelf_life_days': 270,
  'reorder_level': 10,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 20},
 {'name': 'Sunfeast Dark Fantasy Choco Fills',
  'category': 'Biscuits',
  'brand': 'Sunfeast',
  'unit': '75g pack',
  'mrp': 35.0,
  'purchase_price': 30.45,
  'shelf_life_days': 240,
  'reorder_level': 8,
  'hsn': '1905',
  'supplier': 'Sharma Distributors',
  'qty': 18},
 {'name': 'Parle Hide & Seek 100g',
  'category': 'Biscuits',
  'brand': 'Parle',
  'unit': '100g pack',
  'mrp': 35.0,
  'purchase_price': 30.45,
  'shelf_life_days': 240,
  'reorder_level': 8,
  'hsn': '1905',
  'supplier': 'Sharma Distributors',
  'qty': 17},
 {'name': 'Oreo Vanilla Cream 120g',
  'category': 'Biscuits',
  'brand': 'Cadbury',
  'unit': '120g pack',
  'mrp': 40.0,
  'purchase_price': 34.8,
  'shelf_life_days': 270,
  'reorder_level': 8,
  'hsn': '1905',
  'supplier': 'Mondelez Beat Sales',
  'qty': 15},
 {'name': 'Britannia Rusk Premium Bake 200g',
  'category': 'Biscuits',
  'brand': 'Britannia',
  'unit': '200g pack',
  'mrp': 45.0,
  'purchase_price': 39.6,
  'shelf_life_days': 120,
  'reorder_level': 8,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 16},
 {'name': 'Britannia White Bread 400g',
  'category': 'Bread',
  'brand': 'Britannia',
  'unit': '400g loaf',
  'mrp': 45.0,
  'purchase_price': 39.15,
  'shelf_life_days': 5,
  'reorder_level': 12,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 16},
 {'name': 'Britannia Brown Bread 400g',
  'category': 'Bread',
  'brand': 'Britannia',
  'unit': '400g loaf',
  'mrp': 55.0,
  'purchase_price': 47.85,
  'shelf_life_days': 6,
  'reorder_level': 8,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 5},
 {'name': 'Modern Milk Bread 400g',
  'category': 'Bread',
  'brand': 'Modern',
  'unit': '400g loaf',
  'mrp': 50.0,
  'purchase_price': 43.5,
  'shelf_life_days': 5,
  'reorder_level': 6,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 10},
 {'name': 'Britannia Pav 6pc',
  'category': 'Bread',
  'brand': 'Britannia',
  'unit': '6 pcs pack',
  'mrp': 35.0,
  'purchase_price': 30.45,
  'shelf_life_days': 4,
  'reorder_level': 6,
  'hsn': '1905',
  'supplier': 'Britannia Super Stockist',
  'qty': 12},
 {'name': 'Table Eggs (loose)',
  'category': 'Eggs',
  'brand': 'Local',
  'unit': 'per egg',
  'mrp': 7.0,
  'purchase_price': 6.02,
  'shelf_life_days': 12,
  'reorder_level': 60,
  'hsn': None,
  'supplier': 'Rajesh Egg Supply',
  'qty': 90},
 {'name': 'Eggs Tray (30)',
  'category': 'Eggs',
  'brand': 'Local',
  'unit': '30 tray',
  'mrp': 200.0,
  'purchase_price': 176.0,
  'shelf_life_days': 12,
  'reorder_level': 8,
  'hsn': None,
  'supplier': 'Rajesh Egg Supply',
  'qty': 14},
 {'name': 'Brown Eggs 6-pack',
  'category': 'Eggs',
  'brand': 'Local',
  'unit': '6 pack',
  'mrp': 72.0,
  'purchase_price': 62.64,
  'shelf_life_days': 12,
  'reorder_level': 6,
  'hsn': None,
  'supplier': 'Rajesh Egg Supply',
  'qty': 9},
 {'name': "Lay's Classic Salted Rs20",
  'category': 'Snacks',
  'brand': "Lay's",
  'unit': '52g pack',
  'mrp': 20.0,
  'purchase_price': 17.2,
  'shelf_life_days': 120,
  'reorder_level': 24,
  'hsn': '2005',
  'supplier': 'PepsiCo Snacks Van',
  'qty': 56},
 {'name': "Lay's Magic Masala Rs10",
  'category': 'Snacks',
  'brand': "Lay's",
  'unit': '26g pack',
  'mrp': 10.0,
  'purchase_price': 8.6,
  'shelf_life_days': 120,
  'reorder_level': 30,
  'hsn': '2005',
  'supplier': 'PepsiCo Snacks Van',
  'qty': 70},
 {'name': 'Kurkure Masala Munch Rs20',
  'category': 'Snacks',
  'brand': 'Kurkure',
  'unit': '82g pack',
  'mrp': 20.0,
  'purchase_price': 17.0,
  'shelf_life_days': 120,
  'reorder_level': 24,
  'hsn': '2106',
  'supplier': 'PepsiCo Snacks Van',
  'qty': 52},
 {'name': 'Kurkure Rs10',
  'category': 'Snacks',
  'brand': 'Kurkure',
  'unit': '38g pack',
  'mrp': 10.0,
  'purchase_price': 8.5,
  'shelf_life_days': 120,
  'reorder_level': 30,
  'hsn': '2106',
  'supplier': 'PepsiCo Snacks Van',
  'qty': 64},
 {'name': 'Bingo Mad Angles Rs20',
  'category': 'Snacks',
  'brand': 'Bingo',
  'unit': '66g pack',
  'mrp': 20.0,
  'purchase_price': 17.0,
  'shelf_life_days': 120,
  'reorder_level': 16,
  'hsn': '2005',
  'supplier': 'Sharma Distributors',
  'qty': 30},
 {'name': 'Haldiram Aloo Bhujia 200g',
  'category': 'Snacks',
  'brand': 'Haldiram',
  'unit': '200g pack',
  'mrp': 55.0,
  'purchase_price': 46.2,
  'shelf_life_days': 150,
  'reorder_level': 12,
  'hsn': '2106',
  'supplier': 'Ganesh Provision Stores',
  'qty': 26},
 {'name': 'Haldiram Aloo Bhujia 1kg',
  'category': 'Snacks',
  'brand': 'Haldiram',
  'unit': '1kg pack',
  'mrp': 230.0,
  'purchase_price': 195.5,
  'shelf_life_days': 150,
  'reorder_level': 4,
  'hsn': '2106',
  'supplier': 'Ganesh Provision Stores',
  'qty': 7},
 {'name': 'Haldiram Navratan Mixture 350g',
  'category': 'Snacks',
  'brand': 'Haldiram',
  'unit': '350g pack',
  'mrp': 90.0,
  'purchase_price': 75.6,
  'shelf_life_days': 150,
  'reorder_level': 6,
  'hsn': '2106',
  'supplier': 'Ganesh Provision Stores',
  'qty': 11},
 {'name': 'Balaji Wafers Masala 45g',
  'category': 'Snacks',
  'brand': 'Balaji',
  'unit': '45g pack',
  'mrp': 10.0,
  'purchase_price': 8.2,
  'shelf_life_days': 120,
  'reorder_level': 20,
  'hsn': '2005',
  'supplier': 'Ganesh Provision Stores',
  'qty': 44},
 {'name': 'Tata Tea Premium 250g',
  'category': 'Tea & Coffee',
  'brand': 'Tata Tea',
  'unit': '250g pack',
  'mrp': 145.0,
  'purchase_price': 130.5,
  'shelf_life_days': 540,
  'reorder_level': 10,
  'hsn': '0902',
  'supplier': 'Gupta Trading Co.',
  'qty': 24},
 {'name': 'Tata Tea Premium 500g',
  'category': 'Tea & Coffee',
  'brand': 'Tata Tea',
  'unit': '500g pack',
  'mrp': 280.0,
  'purchase_price': 252.0,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '0902',
  'supplier': 'Gupta Trading Co.',
  'qty': 12},
 {'name': 'Red Label Tea 250g',
  'category': 'Tea & Coffee',
  'brand': 'Brooke Bond',
  'unit': '250g pack',
  'mrp': 120.0,
  'purchase_price': 108.0,
  'shelf_life_days': 540,
  'reorder_level': 10,
  'hsn': '0902',
  'supplier': 'Gupta Trading Co.',
  'qty': 22},
 {'name': 'Red Label Tea 500g',
  'category': 'Tea & Coffee',
  'brand': 'Brooke Bond',
  'unit': '500g pack',
  'mrp': 232.0,
  'purchase_price': 208.8,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '0902',
  'supplier': 'Gupta Trading Co.',
  'qty': 11},
 {'name': 'Nescafe Classic 50g Jar',
  'category': 'Tea & Coffee',
  'brand': 'Nescafe',
  'unit': '50g jar',
  'mrp': 165.0,
  'purchase_price': 148.5,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '0901',
  'supplier': 'Verma Agencies',
  'qty': 14},
 {'name': 'Bru Instant Coffee 50g',
  'category': 'Tea & Coffee',
  'brand': 'Bru',
  'unit': '50g jar',
  'mrp': 155.0,
  'purchase_price': 139.5,
  'shelf_life_days': 540,
  'reorder_level': 5,
  'hsn': '0901',
  'supplier': 'Gupta Trading Co.',
  'qty': 10},
 {'name': 'Bournvita 500g Jar',
  'category': 'Tea & Coffee',
  'brand': 'Cadbury',
  'unit': '500g jar',
  'mrp': 245.0,
  'purchase_price': 218.05,
  'shelf_life_days': 365,
  'reorder_level': 5,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 12},
 {'name': 'Horlicks Classic Malt 500g',
  'category': 'Tea & Coffee',
  'brand': 'Horlicks',
  'unit': '500g jar',
  'mrp': 280.0,
  'purchase_price': 249.2,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '1901',
  'supplier': 'Gupta Trading Co.',
  'qty': 9},
 {'name': 'Coca-Cola 750ml',
  'category': 'Cold Drinks',
  'brand': 'Coca-Cola',
  'unit': '750ml PET',
  'mrp': 40.0,
  'purchase_price': 36.0,
  'shelf_life_days': 180,
  'reorder_level': 24,
  'hsn': '2202',
  'supplier': 'Hindustan Beverages',
  'qty': 48},
 {'name': 'Coca-Cola 250ml',
  'category': 'Cold Drinks',
  'brand': 'Coca-Cola',
  'unit': '250ml PET',
  'mrp': 20.0,
  'purchase_price': 18.0,
  'shelf_life_days': 180,
  'reorder_level': 30,
  'hsn': '2202',
  'supplier': 'Hindustan Beverages',
  'qty': 60},
 {'name': 'Thums Up 750ml',
  'category': 'Cold Drinks',
  'brand': 'Thums Up',
  'unit': '750ml PET',
  'mrp': 40.0,
  'purchase_price': 36.0,
  'shelf_life_days': 180,
  'reorder_level': 24,
  'hsn': '2202',
  'supplier': 'Hindustan Beverages',
  'qty': 44},
 {'name': 'Thums Up 2L',
  'category': 'Cold Drinks',
  'brand': 'Thums Up',
  'unit': '2L PET',
  'mrp': 99.0,
  'purchase_price': 90.09,
  'shelf_life_days': 180,
  'reorder_level': 8,
  'hsn': '2202',
  'supplier': 'Hindustan Beverages',
  'qty': 16},
 {'name': 'Sprite 750ml',
  'category': 'Cold Drinks',
  'brand': 'Sprite',
  'unit': '750ml PET',
  'mrp': 40.0,
  'purchase_price': 36.0,
  'shelf_life_days': 180,
  'reorder_level': 18,
  'hsn': '2202',
  'supplier': 'Hindustan Beverages',
  'qty': 32},
 {'name': 'Pepsi 750ml',
  'category': 'Cold Drinks',
  'brand': 'Pepsi',
  'unit': '750ml PET',
  'mrp': 40.0,
  'purchase_price': 36.0,
  'shelf_life_days': 180,
  'reorder_level': 18,
  'hsn': '2202',
  'supplier': 'Varun Beverages',
  'qty': 30},
 {'name': 'Sting Energy Drink 250ml',
  'category': 'Cold Drinks',
  'brand': 'Sting',
  'unit': '250ml PET',
  'mrp': 20.0,
  'purchase_price': 17.6,
  'shelf_life_days': 180,
  'reorder_level': 18,
  'hsn': '2202',
  'supplier': 'Varun Beverages',
  'qty': 40},
 {'name': 'Maaza Mango 600ml',
  'category': 'Cold Drinks',
  'brand': 'Maaza',
  'unit': '600ml PET',
  'mrp': 40.0,
  'purchase_price': 35.6,
  'shelf_life_days': 180,
  'reorder_level': 12,
  'hsn': '2009',
  'supplier': 'Hindustan Beverages',
  'qty': 24},
 {'name': 'Frooti Mango 250ml',
  'category': 'Cold Drinks',
  'brand': 'Frooti',
  'unit': '250ml tetra',
  'mrp': 15.0,
  'purchase_price': 13.05,
  'shelf_life_days': 270,
  'reorder_level': 18,
  'hsn': '2009',
  'supplier': 'Singh Cash & Carry',
  'qty': 36},
 {'name': 'Bisleri Water 1L',
  'category': 'Water',
  'brand': 'Bisleri',
  'unit': '1L bottle',
  'mrp': 20.0,
  'purchase_price': 15.6,
  'shelf_life_days': None,
  'reorder_level': 24,
  'hsn': '2201',
  'supplier': 'Varun Beverages',
  'qty': 48},
 {'name': 'Bisleri Water 2L',
  'category': 'Water',
  'brand': 'Bisleri',
  'unit': '2L bottle',
  'mrp': 30.0,
  'purchase_price': 23.4,
  'shelf_life_days': None,
  'reorder_level': 12,
  'hsn': '2201',
  'supplier': 'Varun Beverages',
  'qty': 28},
 {'name': 'Bisleri Water 500ml',
  'category': 'Water',
  'brand': 'Bisleri',
  'unit': '500ml bottle',
  'mrp': 10.0,
  'purchase_price': 7.5,
  'shelf_life_days': None,
  'reorder_level': 30,
  'hsn': '2201',
  'supplier': 'Varun Beverages',
  'qty': 60},
 {'name': 'Kinley Water 20L Can',
  'category': 'Water',
  'brand': 'Kinley',
  'unit': '20L can',
  'mrp': 80.0,
  'purchase_price': 64.0,
  'shelf_life_days': None,
  'reorder_level': 4,
  'hsn': '2201',
  'supplier': 'Hindustan Beverages',
  'qty': 6},
 {'name': 'Cadbury Dairy Milk Rs10',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': '13.2g bar',
  'mrp': 10.0,
  'purchase_price': 8.8,
  'shelf_life_days': 300,
  'reorder_level': 40,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 90},
 {'name': 'Cadbury Dairy Milk Rs20',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': '34g bar',
  'mrp': 20.0,
  'purchase_price': 17.6,
  'shelf_life_days': 300,
  'reorder_level': 30,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 56},
 {'name': 'Cadbury Dairy Milk Silk 60g',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': '60g bar',
  'mrp': 80.0,
  'purchase_price': 69.6,
  'shelf_life_days': 270,
  'reorder_level': 8,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 16},
 {'name': 'Cadbury Dairy Milk 200g',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': '200g bar',
  'mrp': 250.0,
  'purchase_price': 217.5,
  'shelf_life_days': 270,
  'reorder_level': 3,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 5},
 {'name': 'Cadbury Five Star Rs10',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': '22g bar',
  'mrp': 10.0,
  'purchase_price': 8.7,
  'shelf_life_days': 300,
  'reorder_level': 30,
  'hsn': '1806',
  'supplier': 'Mondelez Beat Sales',
  'qty': 64},
 {'name': 'Nestle KitKat 4-Finger 37g',
  'category': 'Confectionery',
  'brand': 'Nestle',
  'unit': '37g bar',
  'mrp': 40.0,
  'purchase_price': 34.8,
  'shelf_life_days': 270,
  'reorder_level': 12,
  'hsn': '1806',
  'supplier': 'Verma Agencies',
  'qty': 24},
 {'name': 'Nestle Munch Rs10',
  'category': 'Confectionery',
  'brand': 'Nestle',
  'unit': '18g bar',
  'mrp': 10.0,
  'purchase_price': 8.7,
  'shelf_life_days': 270,
  'reorder_level': 24,
  'hsn': '1806',
  'supplier': 'Verma Agencies',
  'qty': 40},
 {'name': 'Perfetti Alpenliebe (jar)',
  'category': 'Confectionery',
  'brand': 'Perfetti',
  'unit': 'per candy',
  'mrp': 1.0,
  'purchase_price': 0.8,
  'shelf_life_days': 365,
  'reorder_level': 100,
  'hsn': '1704',
  'supplier': 'Singh Cash & Carry',
  'qty': 280},
 {'name': 'Cadbury Eclairs (jar)',
  'category': 'Confectionery',
  'brand': 'Cadbury',
  'unit': 'per candy',
  'mrp': 2.0,
  'purchase_price': 1.64,
  'shelf_life_days': 365,
  'reorder_level': 80,
  'hsn': '1704',
  'supplier': 'Mondelez Beat Sales',
  'qty': 190},
 {'name': 'Maggi 2-Min Masala Noodles 70g',
  'category': 'Instant Food',
  'brand': 'Maggi',
  'unit': '70g pack',
  'mrp': 14.0,
  'purchase_price': 12.18,
  'shelf_life_days': 270,
  'reorder_level': 60,
  'hsn': '1902',
  'supplier': 'Verma Agencies',
  'qty': 140},
 {'name': 'Maggi Masala Noodles 4-pack',
  'category': 'Instant Food',
  'brand': 'Maggi',
  'unit': '280g pack',
  'mrp': 56.0,
  'purchase_price': 49.28,
  'shelf_life_days': 270,
  'reorder_level': 20,
  'hsn': '1902',
  'supplier': 'Verma Agencies',
  'qty': 44},
 {'name': 'Maggi Atta Noodles 75g',
  'category': 'Instant Food',
  'brand': 'Maggi',
  'unit': '75g pack',
  'mrp': 22.0,
  'purchase_price': 19.14,
  'shelf_life_days': 270,
  'reorder_level': 12,
  'hsn': '1902',
  'supplier': 'Verma Agencies',
  'qty': 24},
 {'name': 'Yippee Magic Masala Noodles 70g',
  'category': 'Instant Food',
  'brand': 'Sunfeast',
  'unit': '70g pack',
  'mrp': 14.0,
  'purchase_price': 12.18,
  'shelf_life_days': 270,
  'reorder_level': 20,
  'hsn': '1902',
  'supplier': 'Sharma Distributors',
  'qty': 38},
 {'name': 'Maggi Tomato Ketchup 500g',
  'category': 'Instant Food',
  'brand': 'Maggi',
  'unit': '500g bottle',
  'mrp': 99.0,
  'purchase_price': 87.12,
  'shelf_life_days': 365,
  'reorder_level': 8,
  'hsn': '2103',
  'supplier': 'Verma Agencies',
  'qty': 16},
 {'name': 'Kissan Mixed Fruit Jam 200g',
  'category': 'Instant Food',
  'brand': 'Kissan',
  'unit': '200g jar',
  'mrp': 90.0,
  'purchase_price': 79.2,
  'shelf_life_days': 365,
  'reorder_level': 5,
  'hsn': '2007',
  'supplier': 'Gupta Trading Co.',
  'qty': 11},
 {'name': 'Kissan Tomato Ketchup 850g',
  'category': 'Instant Food',
  'brand': 'Kissan',
  'unit': '850g bottle',
  'mrp': 140.0,
  'purchase_price': 123.2,
  'shelf_life_days': 365,
  'reorder_level': 5,
  'hsn': '2103',
  'supplier': 'Gupta Trading Co.',
  'qty': 9},
 {'name': 'MTR Rava Idli Mix 500g',
  'category': 'Instant Food',
  'brand': 'MTR',
  'unit': '500g pack',
  'mrp': 95.0,
  'purchase_price': 82.65,
  'shelf_life_days': 240,
  'reorder_level': 4,
  'hsn': '1106',
  'supplier': 'Ganesh Provision Stores',
  'qty': 8},
 {'name': "Mother's Recipe Mango Pickle 300g",
  'category': 'Instant Food',
  'brand': "Mother's Recipe",
  'unit': '300g jar',
  'mrp': 85.0,
  'purchase_price': 73.95,
  'shelf_life_days': 540,
  'reorder_level': 4,
  'hsn': '2001',
  'supplier': 'Ganesh Provision Stores',
  'qty': 9},
 {'name': 'Colgate Dental Cream 100g',
  'category': 'Personal Care',
  'brand': 'Colgate',
  'unit': '100g tube',
  'mrp': 76.0,
  'purchase_price': 64.6,
  'shelf_life_days': 730,
  'reorder_level': 12,
  'hsn': '3306',
  'supplier': 'Singh Cash & Carry',
  'qty': 26},
 {'name': 'Colgate Dental Cream 200g',
  'category': 'Personal Care',
  'brand': 'Colgate',
  'unit': '200g tube',
  'mrp': 130.0,
  'purchase_price': 110.5,
  'shelf_life_days': 730,
  'reorder_level': 8,
  'hsn': '3306',
  'supplier': 'Singh Cash & Carry',
  'qty': 16},
 {'name': 'Colgate ZigZag Toothbrush',
  'category': 'Personal Care',
  'brand': 'Colgate',
  'unit': '1 pc',
  'mrp': 35.0,
  'purchase_price': 28.0,
  'shelf_life_days': None,
  'reorder_level': 12,
  'hsn': '9603',
  'supplier': 'Singh Cash & Carry',
  'qty': 28},
 {'name': 'Lifebuoy Soap 100g',
  'category': 'Personal Care',
  'brand': 'Lifebuoy',
  'unit': '100g bar',
  'mrp': 35.0,
  'purchase_price': 29.4,
  'shelf_life_days': 730,
  'reorder_level': 18,
  'hsn': '3401',
  'supplier': 'Gupta Trading Co.',
  'qty': 40},
 {'name': 'Lux Soap 100g',
  'category': 'Personal Care',
  'brand': 'Lux',
  'unit': '100g bar',
  'mrp': 45.0,
  'purchase_price': 37.8,
  'shelf_life_days': 730,
  'reorder_level': 14,
  'hsn': '3401',
  'supplier': 'Gupta Trading Co.',
  'qty': 30},
 {'name': 'Clinic Plus Shampoo 175ml',
  'category': 'Personal Care',
  'brand': 'Clinic Plus',
  'unit': '175ml bottle',
  'mrp': 99.0,
  'purchase_price': 83.16,
  'shelf_life_days': 540,
  'reorder_level': 8,
  'hsn': '3305',
  'supplier': 'Gupta Trading Co.',
  'qty': 17},
 {'name': 'Head & Shoulders 180ml',
  'category': 'Personal Care',
  'brand': 'Head & Shoulders',
  'unit': '180ml bottle',
  'mrp': 175.0,
  'purchase_price': 145.25,
  'shelf_life_days': 540,
  'reorder_level': 5,
  'hsn': '3305',
  'supplier': 'Singh Cash & Carry',
  'qty': 11},
 {'name': 'Clinic Plus Shampoo Sachet Rs3',
  'category': 'Personal Care',
  'brand': 'Clinic Plus',
  'unit': 'sachet',
  'mrp': 3.0,
  'purchase_price': 2.46,
  'shelf_life_days': 540,
  'reorder_level': 60,
  'hsn': '3305',
  'supplier': 'Gupta Trading Co.',
  'qty': 160},
 {'name': 'Parachute Coconut Oil 200ml',
  'category': 'Personal Care',
  'brand': 'Parachute',
  'unit': '200ml bottle',
  'mrp': 110.0,
  'purchase_price': 94.6,
  'shelf_life_days': 540,
  'reorder_level': 8,
  'hsn': '3305',
  'supplier': 'Marico D2R',
  'qty': 18},
 {'name': 'Dabur Amla Hair Oil 200ml',
  'category': 'Personal Care',
  'brand': 'Dabur',
  'unit': '200ml bottle',
  'mrp': 120.0,
  'purchase_price': 102.0,
  'shelf_life_days': 540,
  'reorder_level': 6,
  'hsn': '3305',
  'supplier': 'Singh Cash & Carry',
  'qty': 13},
 {'name': 'Gillette Guard Razor',
  'category': 'Personal Care',
  'brand': 'Gillette',
  'unit': '1 pc',
  'mrp': 30.0,
  'purchase_price': 24.6,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '8212',
  'supplier': 'Singh Cash & Carry',
  'qty': 18},
 {'name': 'Whisper Ultra Sanitary Pads (7)',
  'category': 'Personal Care',
  'brand': 'Whisper',
  'unit': '7 pads',
  'mrp': 95.0,
  'purchase_price': 79.8,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '9619',
  'supplier': 'Singh Cash & Carry',
  'qty': 12},
 {'name': 'Surf Excel Easy Wash 1kg',
  'category': 'Home Care',
  'brand': 'Surf Excel',
  'unit': '1kg pack',
  'mrp': 140.0,
  'purchase_price': 121.8,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '3402',
  'supplier': 'Gupta Trading Co.',
  'qty': 18},
 {'name': 'Ariel Matic Detergent 1kg',
  'category': 'Home Care',
  'brand': 'Ariel',
  'unit': '1kg pack',
  'mrp': 230.0,
  'purchase_price': 197.8,
  'shelf_life_days': None,
  'reorder_level': 5,
  'hsn': '3402',
  'supplier': 'Singh Cash & Carry',
  'qty': 10},
 {'name': 'Tide Plus 1kg',
  'category': 'Home Care',
  'brand': 'Tide',
  'unit': '1kg pack',
  'mrp': 110.0,
  'purchase_price': 94.6,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '3402',
  'supplier': 'Singh Cash & Carry',
  'qty': 14},
 {'name': 'Nirma Washing Powder 1kg',
  'category': 'Home Care',
  'brand': 'Nirma',
  'unit': '1kg pack',
  'mrp': 70.0,
  'purchase_price': 57.4,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '3402',
  'supplier': 'Ganesh Provision Stores',
  'qty': 16},
 {'name': 'Vim Dishwash Bar 200g',
  'category': 'Home Care',
  'brand': 'Vim',
  'unit': '200g bar',
  'mrp': 20.0,
  'purchase_price': 16.6,
  'shelf_life_days': None,
  'reorder_level': 14,
  'hsn': '3401',
  'supplier': 'Gupta Trading Co.',
  'qty': 32},
 {'name': 'Vim Dishwash Liquid 500ml',
  'category': 'Home Care',
  'brand': 'Vim',
  'unit': '500ml bottle',
  'mrp': 120.0,
  'purchase_price': 100.8,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '3402',
  'supplier': 'Gupta Trading Co.',
  'qty': 13},
 {'name': 'Harpic Toilet Cleaner 500ml',
  'category': 'Home Care',
  'brand': 'Harpic',
  'unit': '500ml bottle',
  'mrp': 95.0,
  'purchase_price': 79.8,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '3402',
  'supplier': 'Singh Cash & Carry',
  'qty': 14},
 {'name': 'Lizol Floor Cleaner 500ml',
  'category': 'Home Care',
  'brand': 'Lizol',
  'unit': '500ml bottle',
  'mrp': 99.0,
  'purchase_price': 83.16,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '3402',
  'supplier': 'Singh Cash & Carry',
  'qty': 12},
 {'name': 'Good Knight Refill',
  'category': 'Home Care',
  'brand': 'Good Knight',
  'unit': '45ml refill',
  'mrp': 80.0,
  'purchase_price': 67.2,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '3808',
  'supplier': 'Singh Cash & Carry',
  'qty': 13},
 {'name': 'Nestle Cerelac Wheat-Apple 300g',
  'category': 'Baby Care',
  'brand': 'Cerelac',
  'unit': '300g pack',
  'mrp': 280.0,
  'purchase_price': 252.0,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '1901',
  'supplier': 'Verma Agencies',
  'qty': 9},
 {'name': 'Nestle Nan Pro Stage 1 400g',
  'category': 'Baby Care',
  'brand': 'Nan',
  'unit': '400g tin',
  'mrp': 650.0,
  'purchase_price': 591.5,
  'shelf_life_days': 540,
  'reorder_level': 3,
  'hsn': '1901',
  'supplier': 'Verma Agencies',
  'qty': 5},
 {'name': 'Pampers Diapers M (8)',
  'category': 'Baby Care',
  'brand': 'Pampers',
  'unit': '8 pcs pack',
  'mrp': 199.0,
  'purchase_price': 175.12,
  'shelf_life_days': None,
  'reorder_level': 4,
  'hsn': '9619',
  'supplier': 'Singh Cash & Carry',
  'qty': 8},
 {'name': 'Huggies Wonder Pants S (9)',
  'category': 'Baby Care',
  'brand': 'Huggies',
  'unit': '9 pcs pack',
  'mrp': 210.0,
  'purchase_price': 184.8,
  'shelf_life_days': None,
  'reorder_level': 3,
  'hsn': '9619',
  'supplier': 'Singh Cash & Carry',
  'qty': 6},
 {'name': "Johnson's Baby Powder 200g",
  'category': 'Baby Care',
  'brand': "Johnson's",
  'unit': '200g pack',
  'mrp': 199.0,
  'purchase_price': 173.13,
  'shelf_life_days': 730,
  'reorder_level': 3,
  'hsn': '3304',
  'supplier': 'Singh Cash & Carry',
  'qty': 7},
 {'name': 'Classmate Notebook 172pg',
  'category': 'Stationery',
  'brand': 'Classmate',
  'unit': '1 notebook',
  'mrp': 55.0,
  'purchase_price': 45.1,
  'shelf_life_days': None,
  'reorder_level': 10,
  'hsn': '4820',
  'supplier': 'Singh Cash & Carry',
  'qty': 22},
 {'name': 'Reynolds Ball Pen (Blue)',
  'category': 'Stationery',
  'brand': 'Reynolds',
  'unit': '1 pen',
  'mrp': 10.0,
  'purchase_price': 7.8,
  'shelf_life_days': None,
  'reorder_level': 30,
  'hsn': '9608',
  'supplier': 'Singh Cash & Carry',
  'qty': 70},
 {'name': 'Nataraj Pencil 10-pack',
  'category': 'Stationery',
  'brand': 'Nataraj',
  'unit': '10 pcs',
  'mrp': 50.0,
  'purchase_price': 40.0,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '9609',
  'supplier': 'Singh Cash & Carry',
  'qty': 18},
 {'name': 'Eveready AA Battery (2)',
  'category': 'Stationery',
  'brand': 'Eveready',
  'unit': '2 pcs',
  'mrp': 40.0,
  'purchase_price': 32.0,
  'shelf_life_days': None,
  'reorder_level': 10,
  'hsn': '8506',
  'supplier': 'Singh Cash & Carry',
  'qty': 24},
 {'name': 'Wipro 9W LED Bulb',
  'category': 'Stationery',
  'brand': 'Wipro',
  'unit': '1 bulb',
  'mrp': 99.0,
  'purchase_price': 81.18,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': '8539',
  'supplier': 'Singh Cash & Carry',
  'qty': 12},
 {'name': 'Cello Sticky Tape',
  'category': 'Stationery',
  'brand': 'Cello',
  'unit': '1 roll',
  'mrp': 25.0,
  'purchase_price': 19.5,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '3919',
  'supplier': 'Singh Cash & Carry',
  'qty': 15},
 {'name': 'Cycle Agarbatti (Three in One)',
  'category': 'Pooja',
  'brand': 'Cycle',
  'unit': '1 pack',
  'mrp': 45.0,
  'purchase_price': 36.9,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '3307',
  'supplier': 'Singh Cash & Carry',
  'qty': 18},
 {'name': 'Mangaldeep Agarbatti',
  'category': 'Pooja',
  'brand': 'Mangaldeep',
  'unit': '1 pack',
  'mrp': 35.0,
  'purchase_price': 28.7,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '3307',
  'supplier': 'Sharma Distributors',
  'qty': 16},
 {'name': 'Camphor (Kapur) 50g',
  'category': 'Pooja',
  'brand': 'Mangalam',
  'unit': '50g pack',
  'mrp': 60.0,
  'purchase_price': 48.0,
  'shelf_life_days': None,
  'reorder_level': 5,
  'hsn': '3307',
  'supplier': 'Singh Cash & Carry',
  'qty': 12},
 {'name': 'Cotton Wicks (Batti) pack',
  'category': 'Pooja',
  'brand': 'Local',
  'unit': '1 pack',
  'mrp': 20.0,
  'purchase_price': 15.0,
  'shelf_life_days': None,
  'reorder_level': 6,
  'hsn': None,
  'supplier': 'Singh Cash & Carry',
  'qty': 14},
 {'name': 'Diya / Deepak (clay) 12pc',
  'category': 'Pooja',
  'brand': 'Local',
  'unit': '12 pcs',
  'mrp': 30.0,
  'purchase_price': 21.0,
  'shelf_life_days': None,
  'reorder_level': 4,
  'hsn': None,
  'supplier': 'Singh Cash & Carry',
  'qty': 9},
 {'name': 'Matchbox (10 boxes)',
  'category': 'Pooja',
  'brand': 'Ship',
  'unit': '10 boxes',
  'mrp': 20.0,
  'purchase_price': 16.0,
  'shelf_life_days': None,
  'reorder_level': 10,
  'hsn': '3605',
  'supplier': 'Singh Cash & Carry',
  'qty': 22},
 {'name': 'Almonds (Badam) loose',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '250g pack',
  'mrp': 230.0,
  'purchase_price': 197.8,
  'shelf_life_days': 365,
  'reorder_level': 5,
  'hsn': '0802',
  'supplier': 'Ganesh Provision Stores',
  'qty': 11},
 {'name': 'Cashews (Kaju) loose',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '250g pack',
  'mrp': 280.0,
  'purchase_price': 240.8,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '0801',
  'supplier': 'Ganesh Provision Stores',
  'qty': 8},
 {'name': 'Raisins (Kishmish) loose',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '250g pack',
  'mrp': 110.0,
  'purchase_price': 93.5,
  'shelf_life_days': 365,
  'reorder_level': 5,
  'hsn': '0806',
  'supplier': 'Ganesh Provision Stores',
  'qty': 12},
 {'name': 'Walnuts (Akhrot) loose',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '250g pack',
  'mrp': 320.0,
  'purchase_price': 275.2,
  'shelf_life_days': 365,
  'reorder_level': 3,
  'hsn': '0802',
  'supplier': 'Ganesh Provision Stores',
  'qty': 5},
 {'name': 'Makhana (Fox Nuts) 100g',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '100g pack',
  'mrp': 90.0,
  'purchase_price': 75.6,
  'shelf_life_days': 365,
  'reorder_level': 4,
  'hsn': '0802',
  'supplier': 'Ganesh Provision Stores',
  'qty': 10},
 {'name': 'Khajoor (Dates) 250g',
  'category': 'Dry Fruits',
  'brand': 'Local',
  'unit': '250g pack',
  'mrp': 120.0,
  'purchase_price': 102.0,
  'shelf_life_days': 240,
  'reorder_level': 4,
  'hsn': '0804',
  'supplier': 'Ganesh Provision Stores',
  'qty': 9},
 {'name': 'Gold Flake Kings 10s',
  'category': 'Tobacco',
  'brand': 'Gold Flake',
  'unit': '10 sticks',
  'mrp': 220.0,
  'purchase_price': 206.8,
  'shelf_life_days': None,
  'reorder_level': 10,
  'hsn': '2402',
  'supplier': 'Singh Cash & Carry',
  'qty': 22},
 {'name': 'Wills Navy Cut 10s',
  'category': 'Tobacco',
  'brand': 'Wills',
  'unit': '10 sticks',
  'mrp': 120.0,
  'purchase_price': 112.8,
  'shelf_life_days': None,
  'reorder_level': 10,
  'hsn': '2402',
  'supplier': 'Singh Cash & Carry',
  'qty': 18},
 {'name': 'Classic Regular 10s',
  'category': 'Tobacco',
  'brand': 'Classic',
  'unit': '10 sticks',
  'mrp': 200.0,
  'purchase_price': 188.0,
  'shelf_life_days': None,
  'reorder_level': 8,
  'hsn': '2402',
  'supplier': 'Singh Cash & Carry',
  'qty': 14},
 {'name': 'Bidi Bundle',
  'category': 'Tobacco',
  'brand': 'Local',
  'unit': '1 bundle',
  'mrp': 25.0,
  'purchase_price': 23.0,
  'shelf_life_days': None,
  'reorder_level': 12,
  'hsn': '2403',
  'supplier': 'Singh Cash & Carry',
  'qty': 26},
 {'name': 'Rajnigandha Paan Masala Rs10',
  'category': 'Tobacco',
  'brand': 'Rajnigandha',
  'unit': 'sachet',
  'mrp': 10.0,
  'purchase_price': 9.0,
  'shelf_life_days': 365,
  'reorder_level': 20,
  'hsn': '2106',
  'supplier': 'Singh Cash & Carry',
  'qty': 40}]
