"""Data layer for Dukaan Saathi — TWO separate SQLite databases.

* ``inventory.db``   — catalog & stock:   suppliers, inventory, purchases
* ``transactions.db`` — money & khata:    customers, sales, ledger (udhaar)

Writes are routed to the owning database (`execute_inv` / `execute_txn`). Reads —
including all LLM-generated SQL — go through a single read-only connection that
``ATTACH``-es BOTH databases as ``inv`` and ``txn``, so the agent can still JOIN
across them (e.g. ``inv.inventory`` ⋈ ``txn.sales``). The SELECT guard
(`run_select`) is the only path LLM SQL takes, and it blocks everything but a
single read query.

Rich, research-grounded demo data is generated by :mod:`dukaan.seed_inventory`
and :mod:`dukaan.seed_ledger`. (Re)build with::

    uv run python -m dukaan.db --reset
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import random
import re
import sqlite3
from pathlib import Path
from typing import Any, Sequence

from dukaan import config

# ============================================================================ schema
INVENTORY_SCHEMA = """
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    phone       TEXT,
    focus       TEXT
);
CREATE TABLE IF NOT EXISTS inventory (
    item_id        INTEGER PRIMARY KEY AUTOINCREMENT,
    name           TEXT NOT NULL,
    category       TEXT,
    brand          TEXT,
    unit           TEXT,
    qty            INTEGER NOT NULL DEFAULT 0,
    mrp            REAL    NOT NULL DEFAULT 0,
    purchase_price REAL    NOT NULL DEFAULT 0,
    expiry_date    TEXT,
    reorder_level  INTEGER DEFAULT 0,
    hsn            TEXT,
    supplier       TEXT
);
CREATE TABLE IF NOT EXISTS purchases (
    purchase_id INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id     INTEGER REFERENCES inventory(item_id),
    supplier    TEXT,
    qty         INTEGER NOT NULL,
    cost        REAL    NOT NULL,
    ts          TEXT    NOT NULL
);
-- One row per receipt-with-distinct-expiry (FEFO batches). inventory.qty is the
-- cached SUM(qty_remaining) over an item's lots; inventory.expiry_date mirrors
-- the earliest OPEN lot. is_estimated=1 when expiry was inferred from shelf-life
-- (challans carry no expiry). A lot is "closed" when qty_remaining = 0.
CREATE TABLE IF NOT EXISTS inventory_lots (
    lot_id         INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id        INTEGER NOT NULL REFERENCES inventory(item_id),
    qty_received   INTEGER NOT NULL,
    qty_remaining  INTEGER NOT NULL,
    expiry_date    TEXT,
    is_estimated   INTEGER NOT NULL DEFAULT 0,
    received_ts    TEXT    NOT NULL,
    supplier       TEXT,
    purchase_price REAL    NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_lots_item_expiry ON inventory_lots(item_id, expiry_date);
"""

TRANSACTIONS_SCHEMA = """
CREATE TABLE IF NOT EXISTS customers (
    customer_id  INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT NOT NULL,
    phone        TEXT,
    credit_limit REAL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS sales (
    sale_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id     INTEGER,
    item_name   TEXT,
    qty         INTEGER NOT NULL,
    sale_price  REAL    NOT NULL,
    ts          TEXT    NOT NULL,
    customer_id INTEGER REFERENCES customers(customer_id)
);
CREATE TABLE IF NOT EXISTS ledger (
    entry_id    INTEGER PRIMARY KEY AUTOINCREMENT,
    customer_id INTEGER REFERENCES customers(customer_id),
    type        TEXT NOT NULL,            -- 'debit' = udhaar taken, 'credit' = repayment
    amount      REAL NOT NULL,
    items       TEXT,
    due_date    TEXT,
    ts          TEXT NOT NULL
);
-- Small key/value store: onboarding session blob + the demo|real data-mode flag.
CREATE TABLE IF NOT EXISTS app_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL,   -- JSON-encoded
    ts    TEXT NOT NULL
);
"""

# Handed to the LLM for text-to-SQL. Both DBs are ATTACH-ed; use the prefixes.
SCHEMA_DESCRIPTION = """\
Two attached SQLite databases for a kirana store — ALWAYS use the schema prefixes:

inv.*  (inventory & stock)
  inv.suppliers(supplier_id, name, phone, focus)
  inv.inventory(item_id, name, category, brand, unit, qty, mrp, purchase_price,
                expiry_date, reorder_level, hsn, supplier)
  inv.purchases(purchase_id, item_id -> inv.inventory.item_id, supplier, qty, cost, ts)
  inv.inventory_lots(lot_id, item_id -> inv.inventory.item_id, qty_received, qty_remaining,
                     expiry_date, is_estimated, received_ts, supplier, purchase_price)
txn.*  (sales, customers & udhaar/khata)
  txn.customers(customer_id, name, phone, credit_limit)
  txn.sales(sale_id, item_id, item_name, qty, sale_price, ts, customer_id -> txn.customers.customer_id)
  txn.ledger(entry_id, customer_id -> txn.customers.customer_id, type, amount, items, due_date, ts)

Notes:
- Money is INR (₹). inv.inventory.qty = current stock on hand (= SUM of its open
  inv.inventory_lots.qty_remaining). inv.inventory.expiry_date mirrors the EARLIEST open lot;
  use inv.inventory_lots for per-batch expiry/FEFO. margin = mrp - purchase_price.
- txn.sales.item_name is the item sold (denormalised; also joinable via item_id to inv.inventory).
- A customer's outstanding udhaar = SUM(amount WHERE type='debit') - SUM(amount WHERE type='credit').
- Dates/timestamps are ISO strings; compare with date('now') / datetime('now','localtime').
- You may JOIN across databases freely, e.g.
    SELECT i.name, SUM(s.qty) FROM txn.sales s JOIN inv.inventory i ON i.item_id=s.item_id GROUP BY i.item_id.
"""


# ====================================================================== connections
def _connect(path: Path, readonly: bool = False) -> sqlite3.Connection:
    if readonly:
        conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=10)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(path, timeout=10)
        conn.execute("PRAGMA foreign_keys=ON;")
    conn.row_factory = sqlite3.Row
    return conn


def get_inventory_conn(readonly: bool = False) -> sqlite3.Connection:
    return _connect(config.INVENTORY_DB_PATH, readonly)


def get_txn_conn(readonly: bool = False) -> sqlite3.Connection:
    return _connect(config.TRANSACTIONS_DB_PATH, readonly)


def get_attached_ro_conn() -> sqlite3.Connection:
    """A read-only scratch connection with BOTH databases attached as ``inv`` and
    ``txn`` — the single read surface for cross-DB analytics and LLM SQL."""
    conn = sqlite3.connect("file:dukaan_ro?mode=memory", uri=True)
    conn.execute(f"ATTACH DATABASE 'file:{config.INVENTORY_DB_PATH}?mode=ro' AS inv")
    conn.execute(f"ATTACH DATABASE 'file:{config.TRANSACTIONS_DB_PATH}?mode=ro' AS txn")
    conn.row_factory = sqlite3.Row
    return conn


# ------------------------------------------------------ trusted internal helpers
def qx(sql: str, params: Sequence[Any] = ()) -> list[dict]:
    """Trusted cross-DB read (both DBs attached as inv/txn). Returns dict rows."""
    conn = get_attached_ro_conn()
    try:
        return [dict(r) for r in conn.execute(sql, tuple(params)).fetchall()]
    finally:
        conn.close()


def _execute(path: Path, sql: str, params: Sequence[Any]) -> int:
    conn = _connect(path)
    try:
        cur = conn.execute(sql, tuple(params))
        conn.commit()
        return int(cur.lastrowid or 0)
    finally:
        conn.close()


def execute_inv(sql: str, params: Sequence[Any] = ()) -> int:
    """Trusted write to inventory.db (suppliers / inventory / purchases)."""
    return _execute(config.INVENTORY_DB_PATH, sql, params)


def execute_txn(sql: str, params: Sequence[Any] = ()) -> int:
    """Trusted write to transactions.db (customers / sales / ledger)."""
    return _execute(config.TRANSACTIONS_DB_PATH, sql, params)


# ===================================================================== SELECT guard
_FORBIDDEN = re.compile(
    r"\b(insert|update|delete|drop|alter|create|replace|attach|detach|"
    r"pragma|vacuum|reindex|truncate|grant|revoke|commit|begin|merge|upsert)\b",
    re.IGNORECASE,
)


def _strip_sql(sql: str) -> str:
    s = (sql or "").strip()
    if s.startswith("```"):
        s = re.sub(r"^```[a-zA-Z]*", "", s).strip()
        if s.endswith("```"):
            s = s[:-3].strip()
    s = re.sub(r"--[^\n]*", " ", s)
    s = re.sub(r"/\*.*?\*/", " ", s, flags=re.DOTALL)
    return s.strip().rstrip(";").strip()


def is_safe_select(sql: str) -> tuple[bool, str]:
    """Return (ok, reason). Only a single SELECT/WITH read query is allowed."""
    s = _strip_sql(sql)
    if not s:
        return False, "empty query"
    if ";" in s:
        return False, "multiple statements are not allowed"
    low = s.lower()
    if not (low.startswith("select") or low.startswith("with")):
        return False, "only SELECT / WITH (read) queries are allowed"
    m = _FORBIDDEN.search(low)
    if m:
        return False, f"forbidden keyword '{m.group(1)}' — reads only"
    return True, "ok"


def run_select(sql: str, max_rows: int = 200) -> dict:
    """Safely execute LLM-generated read SQL across both attached DBs.

    Guarded by `is_safe_select` AND executed on a read-only attached connection.
    Returns {ok, rows, columns, truncated, error}.
    """
    ok, reason = is_safe_select(sql)
    if not ok:
        return {"ok": False, "rows": [], "columns": [], "truncated": False, "error": reason}
    clean = _strip_sql(sql)
    try:
        conn = get_attached_ro_conn()
    except sqlite3.OperationalError as e:
        return {"ok": False, "rows": [], "columns": [], "truncated": False,
                "error": f"could not open databases: {e}"}
    try:
        cur = conn.execute(clean)
        fetched = [dict(r) for r in cur.fetchmany(max_rows + 1)]
        truncated = len(fetched) > max_rows
        cols = [d[0] for d in cur.description] if cur.description else []
        return {"ok": True, "rows": fetched[:max_rows], "columns": cols,
                "truncated": truncated, "error": None}
    except sqlite3.Error as e:
        return {"ok": False, "rows": [], "columns": [], "truncated": False, "error": str(e)}
    finally:
        conn.close()


# =========================================================================== init
def _reset_file(path: Path) -> None:
    for p in (path, path.with_name(path.name + "-wal"), path.with_name(path.name + "-shm")):
        if p.exists():
            p.unlink()


def init_db(seed: bool = True, reset: bool = False) -> None:
    """Create both databases (and optionally seed them from the seed modules)."""
    if reset:
        _reset_file(config.INVENTORY_DB_PATH)
        _reset_file(config.TRANSACTIONS_DB_PATH)

    iconn = get_inventory_conn()
    try:
        iconn.executescript(INVENTORY_SCHEMA)
        iconn.commit()
        already = iconn.execute("SELECT COUNT(*) FROM inventory").fetchone()[0]
    finally:
        iconn.close()
    tconn = get_txn_conn()
    try:
        tconn.executescript(TRANSACTIONS_SCHEMA)
        tconn.commit()
    finally:
        tconn.close()

    if seed and already == 0:
        _seed_all()
    # Ensure the FEFO lots layer exists for every item (idempotent: covers a fresh
    # seed AND any pre-existing un-migrated database).
    backfill_lots()
    if reset:
        set_data_mode("demo")


def _seed_all(end_date: dt.date | None = None) -> None:
    """Load the research-grounded demo data from the seed modules into both DBs."""
    from dukaan import seed_inventory as si  # imported lazily (built by the team)
    from dukaan import seed_ledger as sl

    end = end_date or dt.date.today()
    rnd = random.Random(123)

    # ---------- inventory.db ----------
    iconn = get_inventory_conn()
    try:
        iconn.executemany(
            "INSERT INTO suppliers(name, phone, focus) VALUES (?,?,?)",
            [(s.get("name"), s.get("phone"), s.get("focus")) for s in si.SUPPLIERS],
        )
        inv_rows = []
        for it in si.CATALOG:
            sl_days = it.get("shelf_life_days")
            if sl_days:
                # leave varied remaining shelf life so some items are near expiry
                remaining = max(0, int(sl_days * rnd.uniform(0.04, 0.9)))
                expiry = (end + dt.timedelta(days=remaining)).isoformat()
            else:
                expiry = None
            inv_rows.append((
                it.get("name"), it.get("category"), it.get("brand"), it.get("unit"),
                int(it.get("qty", 0)), float(it.get("mrp", 0)), float(it.get("purchase_price", 0)),
                expiry, int(it.get("reorder_level", 0)), it.get("hsn"), it.get("supplier"),
            ))
        iconn.executemany(
            "INSERT INTO inventory(name, category, brand, unit, qty, mrp, purchase_price, "
            "expiry_date, reorder_level, hsn, supplier) VALUES (?,?,?,?,?,?,?,?,?,?,?)",
            inv_rows,
        )
        iconn.commit()
        id_of = {r["name"]: r["item_id"] for r in
                 (dict(x) for x in iconn.execute("SELECT item_id, name FROM inventory"))}
        purchases = si.generate_purchases(si.CATALOG, end)
        iconn.executemany(
            "INSERT INTO purchases(item_id, supplier, qty, cost, ts) VALUES (?,?,?,?,?)",
            [(id_of.get(p["item_name"]), p.get("supplier"), int(p["qty"]), float(p["cost"]), p["ts"])
             for p in purchases if p.get("item_name") in id_of],
        )
        iconn.commit()
    finally:
        iconn.close()

    # ---------- transactions.db ----------
    data = sl.generate(si.CATALOG, end)
    tconn = get_txn_conn()
    try:
        tconn.executemany(
            "INSERT INTO customers(name, phone, credit_limit) VALUES (?,?,?)",
            [(c.get("name"), c.get("phone"), float(c.get("credit_limit", 0))) for c in sl.CUSTOMERS],
        )
        tconn.commit()
        cid_of = {r["name"]: r["customer_id"] for r in
                  (dict(x) for x in tconn.execute("SELECT customer_id, name FROM customers"))}
        tconn.executemany(
            "INSERT INTO sales(item_id, item_name, qty, sale_price, ts, customer_id) VALUES (?,?,?,?,?,?)",
            [(id_of.get(s["item_name"]), s["item_name"], int(s["qty"]), float(s["sale_price"]),
              s["ts"], cid_of.get(s.get("customer_name")))
             for s in data["sales"]],
        )
        # "Today so far" — the generated history ends yesterday, so add a lively
        # partial day of fast-mover sales (8am→now) so "aaj ki bikri" is never empty.
        trnd = random.Random(777)
        now = dt.datetime.now()
        start = now.replace(hour=8, minute=0, second=0, microsecond=0)
        span = max(60, int((now - start).total_seconds() // 60))
        fast = [it for it in si.CATALOG if it.get("category") in
                {"Dairy", "Bread", "Eggs", "Biscuits", "Snacks", "Tea & Coffee",
                 "Water", "Cold Drinks", "Staples", "Confectionery"}] or si.CATALOG
        tconn.executemany(
            "INSERT INTO sales(item_id, item_name, qty, sale_price, ts, customer_id) VALUES (?,?,?,?,?,?)",
            [(id_of.get(it["name"]), it["name"], trnd.randint(1, 6), float(it["mrp"]),
              (start + dt.timedelta(minutes=trnd.randint(0, span))).isoformat(timespec="seconds"), None)
             for it in (trnd.choice(fast) for _ in range(trnd.randint(26, 38)))],
        )
        tconn.executemany(
            "INSERT INTO ledger(customer_id, type, amount, items, due_date, ts) VALUES (?,?,?,?,?,?)",
            [(cid_of.get(l["customer_name"]), l["type"], float(l["amount"]),
              l.get("items"), l.get("due_date"), l["ts"])
             for l in data["ledger"] if l.get("customer_name") in cid_of],
        )
        tconn.commit()
    finally:
        tconn.close()


def counts() -> dict:
    """Quick row counts across both DBs (for the CLI + tests)."""
    return {
        "items": qx("SELECT COUNT(*) n FROM inv.inventory")[0]["n"],
        "suppliers": qx("SELECT COUNT(*) n FROM inv.suppliers")[0]["n"],
        "purchases": qx("SELECT COUNT(*) n FROM inv.purchases")[0]["n"],
        "customers": qx("SELECT COUNT(*) n FROM txn.customers")[0]["n"],
        "sales": qx("SELECT COUNT(*) n FROM txn.sales")[0]["n"],
        "ledger": qx("SELECT COUNT(*) n FROM txn.ledger")[0]["n"],
    }


# ===================================================================== app_meta
def meta_get(key: str, default: Any = None) -> Any:
    """Read a JSON value from txn.app_meta (or `default` if absent / corrupt)."""
    rows = qx("SELECT value FROM txn.app_meta WHERE key=?", (key,))
    if not rows:
        return default
    try:
        return json.loads(rows[0]["value"])
    except (ValueError, TypeError):
        return default


def meta_set(key: str, value: Any) -> None:
    """Upsert a JSON value into txn.app_meta."""
    execute_txn(
        "INSERT INTO app_meta(key, value, ts) VALUES (?,?,?) "
        "ON CONFLICT(key) DO UPDATE SET value=excluded.value, ts=excluded.ts",
        (key, json.dumps(value), dt.datetime.now().isoformat(timespec="seconds")),
    )


def data_mode() -> str:
    """'demo' (synthetic seed) or 'real' (owner's onboarded data). Defaults 'demo'."""
    return meta_get("data_mode", "demo")


def set_data_mode(mode: str) -> None:
    meta_set("data_mode", mode)


# ================================================================ lots / migration
def backfill_lots() -> int:
    """Idempotent: ensure every inventory row has >=1 lot. For rows with none,
    create ONE lot mirroring the current qty + expiry (is_estimated=0). Returns the
    number of lots created. Safe to call on every init_db()."""
    rows = qx(
        "SELECT i.item_id, i.qty, i.expiry_date, i.supplier, i.purchase_price "
        "FROM inv.inventory i WHERE NOT EXISTS "
        "(SELECT 1 FROM inv.inventory_lots l WHERE l.item_id = i.item_id)"
    )
    if not rows:
        return 0
    now = dt.datetime.now().isoformat(timespec="seconds")
    conn = get_inventory_conn()
    try:
        conn.executemany(
            "INSERT INTO inventory_lots(item_id, qty_received, qty_remaining, expiry_date, "
            "is_estimated, received_ts, supplier, purchase_price) VALUES (?,?,?,?,?,?,?,?)",
            [(r["item_id"], int(r["qty"]), int(r["qty"]), r["expiry_date"], 0, now,
              r.get("supplier"), float(r["purchase_price"] or 0)) for r in rows],
        )
        conn.commit()
    finally:
        conn.close()
    return len(rows)


def clear_business_data(keep_suppliers: bool = True) -> None:
    """Wipe demo/business rows for the onboarding 'real data' switch. Keeps
    app_meta; keeps suppliers by default (generic reference data)."""
    iconn = get_inventory_conn()
    try:
        iconn.execute("DELETE FROM inventory_lots")
        iconn.execute("DELETE FROM purchases")
        iconn.execute("DELETE FROM inventory")
        if not keep_suppliers:
            iconn.execute("DELETE FROM suppliers")
        iconn.commit()
    finally:
        iconn.close()
    tconn = get_txn_conn()
    try:
        tconn.execute("DELETE FROM sales")
        tconn.execute("DELETE FROM ledger")
        tconn.execute("DELETE FROM customers")
        tconn.commit()
    finally:
        tconn.close()


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Initialise / reset the Dukaan Saathi databases.")
    ap.add_argument("--reset", action="store_true", help="drop and recreate both databases")
    ap.add_argument("--no-seed", dest="seed", action="store_false", help="schemas only, no demo data")
    ap.set_defaults(seed=True)
    args = ap.parse_args()
    init_db(seed=args.seed, reset=args.reset)
    c = counts()
    print(f"inventory.db    -> {c['items']} items, {c['suppliers']} suppliers, {c['purchases']} purchases")
    print(f"transactions.db -> {c['customers']} customers, {c['sales']} sales, {c['ledger']} ledger entries")
